# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

services:
  db:
    image: postgres
    env:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: petclinic

container:
  image: begeek.azurecr.io/ci/petclinic-doc
  endpoint: MyAzureContainerRegistryConnection
  env:
    PGPASSWORD: petclinic

steps:
- task: DownloadSecureFile@1
  name: deployKey
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'

- script: |
    mkdir ~/.ssh && mv $(deployKey.secureFilePath) ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  displayName: 'Configure ssh'

- script: psql -f DDL/01_base.sql -U petclinic -h db
  displayName: 'Setup DB Schema'

- script: |
    mkdir work
    java -jar /schemaspy-6.0.0.jar -o work -t pgsql -dp /drivers -host db -db petclinic -u petclinic -p petclinic
  displayName: 'Execute schemaspy'

- script: |
    cd work
    git init
    git checkout -b gh-pages
    git config --local user.name "t-kiyono"
    git config --local user.email "t-kiyono@be-geek.net"
    git add .
    git commit -m 'gh-pages'
    git push git@github.com:t-kiyono/AzurePipelineTest.git gh-pages -f
  displayName: 'Push to gh-pages'
